### ISSUE TITLE
Support enabling based on file type

### ISSUE THREAD

**Issue by nathansobo** [atom/whitespace#1]
@briandoll wants this because saving in a markdown file disrupts his writing flow.

**Comment by driskell** [comment]
This is now possible. Atom provides language specific configuration for packages.
http://blog.atom.io/2014/10/31/language-scoped-config.html

I think all that's needed is the whitespace package to make its options scoped and then we will be able to configure them in the language-gfm package settings.

**Comment by andronat** [comment]
Any news on that? We really need it for `.md` files :/

**Comment by lee-dohm** [comment]
As far as I know, this has been enabled for a while. There's even a pull request to add some instructions to the README, see https://github.com/atom/whitespace/pull/78.

**Comment by driskell** [comment]
@lee-dohm Ah nice. I can see the source.gfm is hard coded but only for two space. It should just be disabled because gfm allows single space at end of line to simulate new line. Probably needs fixing, and the markdown grammar should probably just disable this so that's another (unless it's done since I last checked!)

**Comment by lee-dohm** [comment]
Actually, according to all of the Markdown specs I've read, the line break thing requires "two or more spaces":

http://daringfireball.net/projects/markdown/syntax#p

> When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

**Comment by lee-dohm** [comment]
Since I just merged #78 and opened #80. I'm going to close this. If I missed something, please let me know!

**Comment by driskell** [comment]
Thanks! Not sure where I got one space from heh, sorry!
