### ISSUE TITLE
Remove trailing whitespace should be off by default

### ISSUE THREAD

**Issue by jaw-sh** [atom/whitespace#103]
You locked the prior issue on this but I installed Atom only to have it fucking obliterate my documents's perfect whitespacing. Your preference should not be inflicted on me for daring to open my files with your editor. Either make this extension off by default or make this setting off by default. You do not know better than me, stop pretending to.

**Comment by lee-dohm** [comment]
As was stated in the previous Issue, #10, we don't currently intend on changing the default or having the package disabled by default. Thanks for your feedback.
