### ISSUE TITLE
Atom doesn't update Tab Type after "Convert Spaces To Tabs"

### ISSUE THREAD

**Issue by alexchandel** [atom/whitespace#109]
Possible migration from atom/atom#10745.

After converting a file from space-based indentation to tab-based indentation (or vice versa), Atom continues to insert spaces (or tabs) for newlines or tab-keypresses.

If the "Tab Type" is "auto", then a current workaround is to close and reopen the file. However this should *not* be necessary. Changing "the file's tab type" should be immediately detected.

Edit: for reference, this issue does not refer to "Tab Type" setting. It refers to the current indentation method Atom thinks a file is using *when the Tab Type setting is auto*, and therefore what is inserted when the tab key is pressed.

**Comment by alexchandel** [comment]
@lee-dohm How is this not a bug?

If I convert all tabs to spaces, then close and reopen the tab, the Tab Type is detected to be spaces. However, despite "auto"'s claim that it will use the first type of indentation it encounters, this detection does not happen here, and despite there being **zero** tabs in the file, it still inserts tabs.

Moreover to my knowledge there is no way to change this internal perception.

**Comment by dylanjameswagner** [comment]
I believe the auto detection is at the time the file is opened and doesn't change when whitespace is converted. I've been using Tab Control as a secondary step to change the documents tab setting.

**Comment by alexchandel** [comment]
@dylanjameswagner Makes sense. But it **should** change. Otherwise the editor window is just in a broken state.
