### ISSUE TITLE
Ensure a number of trailing newline should not be the default

### ISSUE THREAD

**Issue by PurHur** [atom/whitespace#111]
Discussion:
Ensure a number of trailing newline should not be the default behaviour because its very unlikly the user expect this new line at all of his files.

**Comment by lee-dohm** [comment]
Thank you for the feedback. We've heard a lot of discussion on the defaults of this package. We're not open to changing the defaults.

Thanks for your interest in Atom!

**Comment by spocke** [comment]
I think this should be re opened. It becomes really annoying when working with third party projects or getting pull requests where the last line of the file gets updated. I guess it's good to normalize but it should be opt-in and not enabled by default.

If editor IDE A adds a line break and editor IDE B trims it it will be a constant struggle.

Flicking this one off by default wouldn't break any existing projects either. A.f.a.i.k Atom is the only editor that does this.

I hope you guys reconsider.

**Comment by 50Wliu** [comment]
Please see #10 for the rationale behind this setting being on by default.

**Comment by johncbowers** [comment]
For what its worth, vim, emacs, and echo "abcd" > myfile.txt all add the newline. For instance, in vim if you open a file without a newline and immediately save the newline gets added.

**Comment by PurHur** [comment]
You are allowed to open all files in Atom. Like files that dont want to have a trailing end new line. It breaks the shit every time if you are not aware of that "feature" aka bug.

**Comment by lee-dohm** [comment]
@PurHur your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as is unprofessional conduct. You may consider this an official warning.
