### ISSUE TITLE
Problem getting syntax-scoped setting to work

### ISSUE THREAD

**Issue by lonsun** [atom/whitespace#112]
Hi,

I'm trying to disable the "Ensure Single Trailing Newline" option for crontab files. I put 

    "*":
        ...
        '.source.crontab':
            whitespace:
                ensureSingleTrailingNewline: false

into config.cson.  I restarted Atom and it automtically reformatted that to:

    "*":
        ...
        source:
            crontab:
                whitespace:
                    ensureSingleTrailingNewline: false

But it is still removing extra newlines at the end of the file.  I validated in dev tools that the grammar (appears) to be correct:

`<atom-text-editor class="editor" tabindex="-1" data-grammar="source crontab" data-encoding="utf8" style=""></atom-text-editor>`

Maybe I'm just not configuring it right, but I have not been able to find clear documentation on syntax-scoped configurations.  Any help would be appreciated.

**Comment by lee-dohm** [comment]
The `"*"` is designed to match all scopes (it's the "all languages" signifier). So your specifier of `.source.crontab` is at the wrong level. What you need to do is reformat it like this:

```
"*":
  ...
'.source.crontab':
  whitespace:
    ensureSingleTrailingNewline: false
```

**Comment by lonsun** [comment]
Thanks for the quick answer @lee-dohm!  That did it.
