### ISSUE TITLE
Add a keyboard shortcut for stripping whitespace

### ISSUE THREAD

**Issue by maddes** [atom/whitespace#113]
The whitespace stripping is an awesome functionality and I'm glad it can be disabled because I can't just send massive pull requests full of whitespace removal changes in the company projects where I work.

But… there are many others projects (personal and such) in which I'm involved and love the functionality.

But once disabled… always disabled.

So… could I just have a keyboard shortcut to clean the current line/file/selection?

That would be awesome, thanks.

**Comment by 50Wliu** [comment]
You can assign your own custom keyboard shortcut to `whitespace:remove-trailing-whitespace`.  Instructions are available [here](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/), and you should scope it under `atom-workspace`.
