### ISSUE TITLE
Trim whitespace suddenly enabled itself

### ISSUE THREAD

**Issue by rejhgadellaa** [atom/whitespace#114]
I'm pretty sure I had it turned off. Not sure if I disabled the entire package or disabled an option but I suddenly found Atom removing trailing whitespace. I put that there for a reason :((

**Comment by 50Wliu** [comment]
@rejhgadellaa Sorry to hear that.  Did you happen to update Atom recently, and can you please paste your `config.cson` file here?  Thanks.

**Comment by lee-dohm** [comment]
@rejhgadellaa As this Issue currently stands, we don't have enough information to take action. Please reopen the Issue if the problem reoccurs or when you can supply the information that @50Wliu asked for.
