### ISSUE TITLE
request: way to save file without trailing whitespace

### ISSUE THREAD

**Issue by dalexj** [atom/whitespace#117]
I really enjoy having this plugin for myself 99% of the time, but every once in a while I want to save a file with trailing whitespace on purpose. Every time I have to go disable the package until I'm done with that file and re-enable it.

is there a way to make a separate save command that won't hook into this package or something similar?

**Comment by mixmatch** [comment]
+1

**Comment by r-chris** [comment]
I am trying to disable this for a certain set of files all together (by filetype), which should be possible according to the readme. In particular I am talking about `cram` test files, but it simply won't work. I thought this should do the trick for all NAME.t files ?

```
"*.t":
  whitespace:
    removeTrailingWhitespace: false
```

**Comment by 50Wliu** [comment]
@r-chris you need the grammar scope of `.t` files.  To find out what that is you can press `Ctrl+Alt+Shift+P` while having a `.t` file open.  The base scope should be the first one listed.

**Comment by 50Wliu** [comment]
There is a PR open implementing this feature at #125.  Any testing would be appreciated.

**Comment by r-chris** [comment]
I would be happy to test it - is there an easy way to pull dev packages into atom?

**Comment by 50Wliu** [comment]
@r-chris `apm develop whitespace`.  Then go to where it was cloned (by default `~/github/whitespace`) and `git checkout wl-save-commands`.  Finally, `atom --dev` to test it out.
