### ISSUE TITLE
request: way to save file without trailing whitespace 

### ISSUE THREAD

**Issue by Canule** [atom/whitespace#119]
Can't get rid of it.

This program has been great so far.
wasting another hour to disable the default crap that's enabled in atom.

**Comment by mixmatch** [comment]
+1

**Comment by mnquintana** [comment]
This is a duplicate of https://github.com/atom/whitespace/issues/117 – feel free to subscribe there for updates. If you want to disable this feature outright, see https://discuss.atom.io/t/why-is-atom-deleting-trailing-whitespace-why-is-there-a-newline-at-the-end-of-the-file-why-are-there-all-these-changes-in-the-file-diff/19189.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
