### ISSUE TITLE
Manually trigger instead of on-save

### ISSUE THREAD

**Issue by ahnbizcad** [atom/whitespace#122]
It would be cool to have the option to trigger certain events manually, perhaps via hotkeys.

Why this is useful/worthwhile:

1) Sometimes, you don't want to make a ton of whitespace changes on certain projects, due to it creating lots of noise in diffs and code reviews.
2) You don't always want to go to the settings to toggle it, especially if you switch frequently between such projects and projects where you do want the whitespace handling on save.
3) You may want to just format the whitespace without actually saving.

Decoupling the formatting and saving can be quite useful that might boost this package up a level.

**Comment by 50Wliu** [comment]
This should already be possible with the `whitespace:remove-trailing-whitespace` command.
