### ISSUE TITLE
Feature Request: scope should be displayed in the footer.

### ISSUE THREAD

**Issue by james-lawrence** [atom/whitespace#129]
instead of having to go to the grammer file to see the scope (less intuitive). there is already a spot at the bottom where the syntax of the file is displayed, adding a hover tooltip for the grammar would make it far easier to find. or some direct link to a the grammar package.

**Comment by 50Wliu** [comment]
@james-lawrence I think you reported this to the wrong repository :wink: (you're probably looking for status-bar).  This sounds like a great idea for a package idea though!
