### ISSUE TITLE
Avoid creating unnecessary whitespace when auto indenting

### ISSUE THREAD

**Issue by iconara** [atom/whitespace#14]
In SublimeText when you press return multiple times the auto indents of the blank lines doesn't remain (I've seen other editors behave like this too, not TextMate though). The way Atom behaves is different, the auto indentation created is left as is. This works poorly with git and other tools that complain about trailing whitespace.

A concrete example, type

```
def hello_world
```

then press return twice, you end up on a line indented two spaces, but the blank line above also has two spaces. Repeat in SublimeText (and many other editors), the blank line above will be completely blank.

To illustrate, this is what you currently end up with (spaces showed as dots, `|` is the caret):

```
def hello_world
··
··|
```

And this is the desired outcome:

```
def hello_world

··|
```

(Please note that this is NOT solved by any strip-trailing-whitespace-on-save feature. That kind of feature is horrible when you work with other people's code and they use an editor that does not srtrip whitespace. Suddenly your one line change ends up as a hundred line diff because your editor decided to strip whitespace from the whole file, not just where you edited. I think editors should only automatically reformat things on lines the user has edited, otherwise collaboration becomes harder).

This might be similar to #13, but I don't know how Xcode behaves so I don't know if the desired behaviour is the same.

**Comment by izuzak** [comment]
I believe this was implemented in https://github.com/atom/whitespace/pull/91. Also see https://github.com/atom/atom/issues/7828 and https://github.com/atom/atom/pull/8514 for more context and discussion.

And here's a note from that PR so that it's easier to figure out when this behavior is applied:

> For this to work, whitespace.removeTrailingWhitespace must be true and whitespace.ignoreWhitespaceOnlyLines must be false as per https://github.com/atom/atom/pull/8514#issuecomment-135127346
