### ISSUE TITLE
Trailing whitespace not being removed

### ISSUE THREAD

**Issue by 50Wliu** [atom/whitespace#158]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Trailing whitespace is not being removed despite the relevant settings being checked.

### Steps to Reproduce

1. Open a file
2. Add some trailing whitespace on one line and move the cursor to a different line
3. Save

**Expected behavior:** Trailing whitespace to be removed

**Actual behavior:** Trailing whitespace remains

**Reproduces how often:** 100%

### Versions
```
Atom    : 1.20.0-dev-ac99e0861
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
Windows 10 x64

### Additional Information

/cc @maxbrunsfeld

**Comment by borishere** [comment]
Oh nooo, I have too much trailing whitespaces now:(

**Comment by maxbrunsfeld** [comment]
Sorry about this everyone. We'll release a hotfix shortly.
