### ISSUE TITLE
Trailing whitespace is not being removed

### ISSUE THREAD

**Issue by zhangshenxu** [atom/whitespace#171]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Trailing whitespace is not being removed despite the relevant settings being checked.

### Steps to Reproduce

1. Open a file
2. Add some trailing whitespace on one line and move the cursor to a different line
3. Save

**Expected behavior:** Trailing whitespace to be removed

**Actual behavior:** Trailing whitespace remains

**Reproduces how often:** 100%

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
macOS High Sierra 10.13.2

**Comment by rsese** [comment]
Thanks for the report - does this happen for any file type or just particular files?  I'm unable to reproduce if I have `Remove Trailing Whitespace` checked on macOS 10.12.6 with Atom 1.23.3.

**Comment by zhangshenxu** [comment]
it happens for any file type. I use the default setting, no idea why it doesn't work

**Comment by rsese** [comment]
Can you share a GIF/screencast of the behavior in safe mode?  If you can also turn on invisible (`Settings > Editor > Show Invisibles`), that would be helpful too.

**Comment by zhangshenxu** [comment]
i upgrade to 1.24.0 then it looks well, thanks

**Comment by 50Wliu** [comment]
:+1:
