### ISSUE TITLE
Revisit Issue #10 > "Remove Trailing Whitespace" should not be on by default

### ISSUE THREAD

**Issue by ccoenen** [atom/whitespace#43]
Since the [issue](https://github.com/atom/whitespace/issues/10) has been closed, a lot of people have asked you to reconsider. Personally, i think that this issue has been closed too early.

Yes, trailing whitespace is not per se neccessary, but making changes to code _just_ to conform to coding style is unneccessary, too. And in some cases (mentioned in #10 as well), this change can be destructive.

You're trying to prevent churn, and i get that. But you're creating churn with this, yourselves.

Then, there's people who don't use atom (*gosh* i know). I don't want to clean up other people's white space after them. Most certainly not incidentally.

**Comment by slang800** [comment]
See https://github.com/sindresorhus/atom-editorconfig/issues/3 with regards to editorconfig

> I don't want to clean up other people's white space after them. Most certainly not incidentally.

...add this to your config.cson if you don't want to do that:
```
'global':
  'whitespace':
    'removeTrailingWhitespace': false
```

Lastly, if you want #10 to be reopened, then go comment there... making duplicate issues isn't the way to go.

**Comment by ccoenen** [comment]
Yes, i commented there as well. And i had the impression that the atom team does not discuss there since it was closed. So i opened an issue to get their attention back to the topic.

In case you missed it, I also created #59. Yes, i'm serious. Feel free to add your opinion there, too.

**Comment by 50Wliu** [comment]
Let's keep the discussion over at #10 for now, regardless if it's closed.
