### ISSUE TITLE
File autoload and append a newline when disabling whitespace.ensureSingleTrailingNewline

### ISSUE THREAD

**Issue by 50Wliu** [atom/whitespace#58]
_From @fundon on February 20, 2015 20:20_

The `whitespace.ensureSingleTrailingNewline` was disabled.
But it still appends a newline.

My steps:

0. open `package.json` in Atom
0. exec command `$ npm i xx@latest --save` in Terminal

_Copied from original issue: atom/atom#5656_

**Comment by 50Wliu** [comment]
Can you reproduce this using `atom --safe`?
What Atom version are you using?

**Comment by 50Wliu** [comment]
_From @fundon on February 20, 2015 20:54_

The latest version v0.182.0.
And using `atom --safe`, it's also happend.

**Comment by greencopper** [comment]
This is a still an issue for me on v1.8.0

**Comment by 50Wliu** [comment]
Thanks for the update @greencopper!  I'm closing this until someone else can reproduce it.
