### ISSUE TITLE
'Trailing white space' plugin should ignore files with .MD extension

### ISSUE THREAD

**Issue by vinyar** [atom/whitespace#62]
Trailing white spaces are part of the Markdown syntax. 

As mentioned many times in this bug: https://github.com/atom/whitespace/issues/10
Markdown files should be filtered out of the plugin 'magic'

**Comment by vinyar** [comment]
A very interesting positive side effect - after disabling the plugin, the markdown preview generation is substantially faster

**Comment by slang800** [comment]
just add this to your config:

```
".gfm.source":
  whitespace:
    removeTrailingWhitespace: false
```

The docs for scoped settings are here: http://blog.atom.io/2014/10/31/language-scoped-config.html

From what I've seen, most users don't write markdown that makes use of trailing white-spaces to indicate formatting, so it doesn't make sense to have this be off by default.

**Comment by ccoenen** [comment]
@slang800 dismissing a feature of a grammar (br-tags with two spaces at the EOL) based on your perspective is hardly useful.

With that attitude, i could say "hey, i don't know anyone who uses closures in JavaScript. Let's just strip them". I'm exxagerating, of course, but it IS a feature of MarkDown. And you don't get to choose if it is important or not.

**Comment by vinyar** [comment]
@slang800 Thanks. This is good info for power users. I used Atom for a few days now, and it seems like a pretty major oversight to support a language but ignore some of its base syntax (thus this bug/enhancement) request.
@ccoenen +1

**Comment by lee-dohm** [comment]
To my understanding this is currently baked into the code here:

https://github.com/atom/whitespace/blob/master/lib/whitespace.coffee#L59-L63

Because of this, I'm going to close this Issue. If I'm making a mistake, I trust everyone to tell me :grinning:
