### ISSUE TITLE
failing to remove whitespace from markdown file

### ISSUE THREAD

**Issue by slang800** [atom/whitespace#68]
I ran into a markdown file that had a bunch of trailing whitespace. None of it was actually required for it to render properly, it was just there by mistake. So I opened & saved the file with Atom, expecting it to be stripped, but only some of it was (all the lines with 2 trailing spaces remained). Using the "Whitespace: Remove Trailing Whitespace" command also failed to strip it.

I think that [this is the code responsible](https://github.com/atom/whitespace/blob/466e130328e3ddd2a097989b6f4edc256d084bd3/lib/whitespace.coffee#L60) - some special logic for leaving 2 spaces alone in GFM.

I propose that we either remove this, since nearly the same thing can be accomplished if people who use trailing whitespace in their markdown added the following to their config:

```cson
".gfm.source":
  whitespace:
    removeTrailingWhitespace: false
```

...or at least make enabling it an option, since I only found out about it by reading the source.

**Comment by mik01aj** [comment]
I'm having the same issue. I select some text in MD file, choose "Remove trailing whitespace" from menu and nothing happens.

Using Atom 1.4.1.

**Comment by slang800** [comment]
There was a new configuration option introduced by https://github.com/atom/whitespace/commit/5004bf72668acdc12a2a8f3604e7bfabcf64e242 that you have to edit

**Comment by mik01aj** [comment]
I understand that you're talking about settings for automatic removing of whitespace when I save the file. This isn't the case here: I'm explicitly asking Atom to remove trailing whitespace by selecting the relevant menu option. Whatever the config, this option should definitely do what it says.

**Comment by slang800** [comment]
Yeah, that would make sense (especially if you're running it on a selection), but [this block](https://github.com/atom/whitespace/blob/af9edc6fcc739ac0e45674b67b45b25479f42f01/lib/whitespace.coffee#L59-L63) of code is what's getting run, no matter whether it's triggered manually or on save.

**Comment by mik01aj** [comment]
Okay, good, so you know where is the bug coming from :blush: 

Shall we reopen it (@lee-dohm) or should I create a new issue?

**Comment by lee-dohm** [comment]
@mik01aj Please open a new issue.
