### ISSUE TITLE
Spaces —> tabs should only convert leading spaces

### ISSUE THREAD

**Issue by ArtskydJ** [atom/whitespace#75]
If I have a file like
```js
var a = {
····x:······3,
····y:······78,
····length:·2
}
```
and I do `whitespace:convert-spaces-to-tabs`, then I expect:
```js
var a = {
————x:······3,
————y:······78,
————length:·2
}
```
but I get:
```js
var a = {
————x:————··3,
————y:————··78,
————length:·2
}
```

tab = ——
space = •

-----

I would like only the leading spaces to be converted. ([Gist](https://gist.github.com/saibotsivad/06021a81865226cfc140))

**Comment by lee-dohm** [comment]
You can get the desired behavior (as well as the undesired behavior) in my [tabs-to-spaces package](https://atom.io/packages/tabs-to-spaces).

**Comment by Alhadis** [comment]
+1, fully seconded.

@lee-dohm : I wouldn't use your package out of principle, simply due to the package's name being back-the-front. xD But that's just me. :p

**Comment by dylanjameswagner** [comment]
+1 this could be a checkbox in settings to scope it to leading whitespace only.

**Comment by Alhadis** [comment]
[Sorted](https://github.com/atom/whitespace/pull/127).
