### ISSUE TITLE
Ignore Whitespace On Current Line doesn't work with split files

### ISSUE THREAD

**Issue by 50Wliu** [atom/whitespace#76]
Steps to reproduce:
1. Open a file
2. Split it
3. On the first split, tab a bit on a random line so that there's some trailing whitespace
4. Keep the cursor on that line in the first split, but not in the second one
5. Save the file

Expected:
Whitespace is preserved since it's on a line with a cursor

Actual:
Whitespace is removed

Atom 0.211.0-ca146c9, Ubuntu 15.04, safe mode.

**Comment by Rush** [comment]
I encountered this as well. It is bugging my crazy! Any ideas how to fix?

**Comment by IanVS** [comment]
Do you have the setting `Ignore Whitespace On Current Line` turned on?

**Comment by 50Wliu** [comment]
Yes.
