### ISSUE TITLE
Remove special case for Markdown in the code

### ISSUE THREAD

**Issue by lee-dohm** [atom/whitespace#80]
See the code here: https://github.com/atom/whitespace/blob/master/lib/whitespace.coffee#L59-L63

There is language-specific configuration for Jade files to disable this by default. This same approach should be used for Markdown.

**Comment by lee-dohm** [comment]
Hmmm ... I see now that it trims whitespace unless it is the magic "two spaces" that Markdown uses for line continuation. I'll have to think more on this.

**Comment by slang800** [comment]
see also: #68

**Comment by mnquintana** [comment]
Fixed in https://github.com/atom/whitespace/issues/82
