### ISSUE TITLE
Feature: Add a massive and visible alert so user is aware that this package makes decisions on the users behalf by default.

### ISSUE THREAD

**Issue by thislakin** [atom/whitespace#83]
This would help others avoid the issue i was having, where i spent $400 figuring out why my files were being changed without my knowledge. 

Cheers

**Comment by thomasjo** [comment]
Thanks for the suggestion, but adding a "massive and visible alert" is not something that's going to happen. If someone implements https://github.com/atom/whitespace/issues/8, I'll propose that it should be enabled by default.

**Comment by granthusbands** [comment]
Because silently corrupting people's text files in a shared repo/environment is clearly preferable to giving them any kind of warning about it?
