### ISSUE TITLE
Converting a 2k lines JSON file from spaces to tabs takes ~15sec

### ISSUE THREAD

**Issue by alexandernst** [atom/whitespace#87]
Converting a ~2k lines (2386) JSON file from spaces to tabs takes around 15 seconds (with the UI completely freezed).

The JSON doesn't have any errors and it has been formatted by an external tool, so this is just a "replace each 4 spaces with 1 tab" operation.

**Comment by 50Wliu** [comment]
@alexandernst would you be able to upload such a file so that I can test this out?

**Comment by alexandernst** [comment]
This isn't an issue anymore with latest stable. I just tried with http://www.json-generator.com/
