### ISSUE TITLE
Request: Option to override soft-tab width

### ISSUE THREAD

**Issue by Alhadis** [atom/whitespace#96]
I see this everywhere: 2-space soft tabs for JavaScript indentation, and it's giving me eye-strain. Since soft tabs aren't configurable the way hard tabs are, there's nothing I can do about it short of modifying the whitespace of whatever file I need to scrutinise.

Since most of the coding world these days refuses to use tabs for absurd reasons ([read this](https://github.com/isaacs/github/issues/170#issuecomment-150489692) before saying anything to that...), Atom could do with a feature to forcefully override the size of leading soft-tabs.

I've created a distracting animation loop to illustrate:

<img src="https://cloud.githubusercontent.com/assets/2346707/10841823/c23d43a2-7f40-11e5-8cf8-03d1515398e6.gif" width="350" /> 

Trying to set the soft-tab width in the theme's stylesheet doesn't work, because soft-tabs are grouped differently based on their size. Furthermore, it seems to wreck havoc on line-wrapping (as you can tell by the mutilated line underneath `ENAMETOOLONG`, the irony of which is just too damn good).

**Comment by Alhadis** [comment]
People should just learn to use hard tabs correctly. 😀 Then the entire world would be at peace.

Why are living backwards? :(

**Comment by Alhadis** [comment]
This is never gonna happen. GitHub hate tabs and probably plot the slow brainwashing of all tab-users. Because Ruby and StandardJS-pollution and what-have-you.

I now cope with the original issue by:

1. [Aggressively reformatting the everloving shit](https://github.com/Alhadis/Atom-PhoenixTheme/blob/d9da1e03831f3b5bc90e593750fb74e1854f6dc8/src/commands/editor.js#L9-L23) out of any 2-space-tab-formatted file I open (<kbd>alt + w</kbd>)

2. Avoiding +90% of other people's JavaScript projects.

3. [Disabling save prompts](https://github.com/Alhadis/Atom-PhoenixTheme/blob/d9da1e03831f3b5bc90e593750fb74e1854f6dc8/src/commands/editor.js#L151-L156) for modified buffers, which means opening, reformatting, and closing ugly JS files doesn't slow me down with a doomed _"Do you wish to save?"_ nag.

4. Shoving tabs where the Atom team don't expect them to go. Usually with irritable and dry-humoured wisecracks in comments or commit logs to distract from the hideous inelegance of whatever brutal hack was committed to version control.

5. Making a point of being a grouchy, opinionated prick wherever the opportunity presents itself, and wearing iconoclasm like a bullet-proof vest.

Tab hard, die young. K&R and BSD for life.

<img width="300" src="https://www.wired.com/wp-content/uploads/blogs/wiredenterprise/wp-content/uploads/2013/01/unix-c.jpg" />

**Comment by xavierfoucrier** [comment]
Hello @Alhadis and @DominicBarnard,

I am working with a developer that have a different coding style from mine: he work with `soft tabs` of `4 spaces` while I am working with `soft tabs` of `2 spaces`, so I have decided to develop a small package that work with an `.editorconfig` file to **detect project coding styles** and apply them to the Atom text editor.

APM: https://atom.io/packages/atom-soft-tabs-length
Github: https://github.com/xavierfoucrier/atom-soft-tabs-length

It's a **minor version**, but you can try it and give a feedback :wink: :tada:
